[package]
name = "ownership-example-usp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
num = "0.4.1"
url = "2.4.1"
